[2025-08-18T10:48:01.359+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T10:45:00+00:00 [queued]>
[2025-08-18T10:48:01.371+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T10:45:00+00:00 [queued]>
[2025-08-18T10:48:01.372+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-08-18T10:48:01.393+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_with_spark> on 2025-08-18 10:45:00+00:00
[2025-08-18T10:48:01.399+0000] {standard_task_runner.py:57} INFO - Started process 545 to run task
[2025-08-18T10:48:01.403+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'nitro_data_pipeline', 'process_with_spark', 'scheduled__2025-08-18T10:45:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpsa82bhar']
[2025-08-18T10:48:01.405+0000] {standard_task_runner.py:85} INFO - Job 259: Subtask process_with_spark
[2025-08-18T10:48:01.469+0000] {task_command.py:410} INFO - Running <TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T10:45:00+00:00 [running]> on host e3730e5f69d2
[2025-08-18T10:48:01.593+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nitro_data_pipeline' AIRFLOW_CTX_TASK_ID='process_with_spark' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T10:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-18T10:45:00+00:00'
[2025-08-18T10:48:01.595+0000] {logging_mixin.py:149} INFO - ===== INICIANDO PROCESO DE SPARK =====
[2025-08-18T12:45:50.941+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-08-18T12:45:51.325+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 545. PIDs of all processes in the group: [546, 545]
[2025-08-18T12:45:51.330+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 545
[2025-08-18T12:45:51.464+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-18T12:45:52.502+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_pipeline.py", line 11, in process_with_spark
    "org.apache.hadoop:hadoop-aws:3.3.1,"
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 103, in launch_gateway
    time.sleep(0.1)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-18T12:45:52.685+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=nitro_data_pipeline, task_id=process_with_spark, execution_date=20250818T104500, start_date=20250818T104801, end_date=20250818T124552
[2025-08-18T12:45:52.961+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 259 for task process_with_spark (Task received SIGTERM signal; 545)
[2025-08-18T12:45:53.032+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=545, status='terminated', exitcode=1, started='10:48:00') (545) terminated with exit code 1
[2025-08-18T12:45:53.039+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=546, status='terminated', started='10:48:00') (546) terminated with exit code None
