[2025-08-18T13:15:18.101+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T13:12:00+00:00 [queued]>
[2025-08-18T13:15:18.149+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T13:12:00+00:00 [queued]>
[2025-08-18T13:15:18.150+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-08-18T13:15:18.470+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_with_spark> on 2025-08-18 13:12:00+00:00
[2025-08-18T13:15:18.600+0000] {standard_task_runner.py:57} INFO - Started process 38818 to run task
[2025-08-18T13:15:18.766+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'nitro_data_pipeline', 'process_with_spark', 'scheduled__2025-08-18T13:12:00+00:00', '--job-id', '387', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpouihxr45']
[2025-08-18T13:15:18.829+0000] {standard_task_runner.py:85} INFO - Job 387: Subtask process_with_spark
[2025-08-18T13:15:20.378+0000] {task_command.py:410} INFO - Running <TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T13:12:00+00:00 [running]> on host e3730e5f69d2
[2025-08-18T13:15:21.803+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nitro_data_pipeline' AIRFLOW_CTX_TASK_ID='process_with_spark' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T13:12:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-18T13:12:00+00:00'
[2025-08-18T13:15:21.809+0000] {logging_mixin.py:149} INFO - ===== INICIANDO PROCESO DE SPARK =====
[2025-08-18T13:16:42.098+0000] {logging_mixin.py:149} INFO - ===== LEYENDO JSON DESDE MINIO =====
[2025-08-18T13:25:19.559+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2025-08-18T13:25:19.776+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 38818. PIDs of all processes in the group: [38819, 38818]
[2025-08-18T13:25:19.955+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 38818
[2025-08-18T13:25:20.272+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-18T13:25:20.382+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-18T13:25:21.392+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-08-18T13:26:51.358+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=38819, name='java', status='sleeping', started='13:15:21') did not respond to SIGTERM. Trying SIGKILL
[2025-08-18T13:26:51.452+0000] {process_utils.py:149} WARNING - process psutil.Process(pid=38818, name='airflow task ru', status='running', started='13:15:18') did not respond to SIGTERM. Trying SIGKILL
[2025-08-18T13:26:51.473+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 38818
[2025-08-18T13:26:52.193+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=38818, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='13:15:18') (38818) terminated with exit code Negsignal.SIGKILL
[2025-08-18T13:26:54.352+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=38819, name='java', status='terminated', started='13:15:21') (38819) terminated with exit code None
[2025-08-18T13:26:54.353+0000] {standard_task_runner.py:174} ERROR - Job 387 was killed before it finished (likely due to running out of memory)
