[2025-08-18T10:47:43.722+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T10:36:00+00:00 [queued]>
[2025-08-18T10:47:43.747+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T10:36:00+00:00 [queued]>
[2025-08-18T10:47:43.748+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 1
[2025-08-18T10:47:43.785+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_with_spark> on 2025-08-18 10:36:00+00:00
[2025-08-18T10:47:43.803+0000] {standard_task_runner.py:57} INFO - Started process 246 to run task
[2025-08-18T10:47:43.811+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'nitro_data_pipeline', 'process_with_spark', 'scheduled__2025-08-18T10:36:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpwgej6a9_']
[2025-08-18T10:47:43.815+0000] {standard_task_runner.py:85} INFO - Job 255: Subtask process_with_spark
[2025-08-18T10:47:43.942+0000] {task_command.py:410} INFO - Running <TaskInstance: nitro_data_pipeline.process_with_spark scheduled__2025-08-18T10:36:00+00:00 [running]> on host e3730e5f69d2
[2025-08-18T10:47:44.182+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nitro_data_pipeline' AIRFLOW_CTX_TASK_ID='process_with_spark' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T10:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-18T10:36:00+00:00'
[2025-08-18T10:47:44.184+0000] {logging_mixin.py:149} INFO - ===== INICIANDO PROCESO DE SPARK =====
[2025-08-18T12:45:50.948+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to None. Terminating instance.
[2025-08-18T12:45:51.336+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 246. PIDs of all processes in the group: [277, 246]
[2025-08-18T12:45:51.342+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 246
[2025-08-18T12:45:51.447+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-18T12:45:52.502+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_pipeline.py", line 11, in process_with_spark
    "org.apache.hadoop:hadoop-aws:3.3.1,"
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 103, in launch_gateway
    time.sleep(0.1)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-18T12:45:52.660+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=nitro_data_pipeline, task_id=process_with_spark, execution_date=20250818T103600, start_date=20250818T104743, end_date=20250818T124552
[2025-08-18T12:45:52.958+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 255 for task process_with_spark (Task received SIGTERM signal; 246)
[2025-08-18T12:45:53.031+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=246, status='terminated', exitcode=1, started='10:47:42') (246) terminated with exit code 1
[2025-08-18T12:45:53.039+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=277, status='terminated', started='10:47:43') (277) terminated with exit code None
