[2025-08-18T13:12:08.580+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nitro_data_pipeline.process_with_spark manual__2025-08-18T13:12:02+00:00 [queued]>
[2025-08-18T13:12:08.677+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nitro_data_pipeline.process_with_spark manual__2025-08-18T13:12:02+00:00 [queued]>
[2025-08-18T13:12:08.678+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-08-18T13:12:08.752+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_with_spark> on 2025-08-18 13:12:02+00:00
[2025-08-18T13:12:08.786+0000] {standard_task_runner.py:57} INFO - Started process 38066 to run task
[2025-08-18T13:12:08.811+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'nitro_data_pipeline', 'process_with_spark', 'manual__2025-08-18T13:12:02+00:00', '--job-id', '385', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline.py', '--cfg-path', '/tmp/tmpaf9ye6ac']
[2025-08-18T13:12:08.821+0000] {standard_task_runner.py:85} INFO - Job 385: Subtask process_with_spark
[2025-08-18T13:12:08.984+0000] {task_command.py:410} INFO - Running <TaskInstance: nitro_data_pipeline.process_with_spark manual__2025-08-18T13:12:02+00:00 [running]> on host e3730e5f69d2
[2025-08-18T13:12:09.707+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='nitro_data_pipeline' AIRFLOW_CTX_TASK_ID='process_with_spark' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T13:12:02+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T13:12:02+00:00'
[2025-08-18T13:12:09.717+0000] {logging_mixin.py:149} INFO - ===== INICIANDO PROCESO DE SPARK =====
[2025-08-18T13:12:59.369+0000] {logging_mixin.py:149} INFO - ===== LEYENDO JSON DESDE MINIO =====
[2025-08-18T13:22:01.271+0000] {logging_mixin.py:149} INFO - Registros le√≠dos: 9696
[2025-08-18T13:22:01.343+0000] {logging_mixin.py:149} INFO - root
 |-- sensor_id: string (nullable = true)
 |-- timestamp: string (nullable = true)
 |-- value: double (nullable = true)
[2025-08-18T13:22:05.160+0000] {logging_mixin.py:149} INFO - +---------+--------------------+-----+
|sensor_id|           timestamp|value|
+---------+--------------------+-----+
| sensor_0|2025-08-16T21:31:...|25.44|
| sensor_3|2025-08-16T21:31:...|27.66|
| sensor_0|2025-08-16T21:31:...|24.79|
| sensor_0|2025-08-16T21:31:...|27.92|
| sensor_1|2025-08-16T21:31:...|23.75|
+---------+--------------------+-----+
only showing top 5 rows
[2025-08-18T13:22:05.706+0000] {logging_mixin.py:149} INFO - ===== CALCULANDO PROMEDIOS =====
[2025-08-18T13:23:20.574+0000] {logging_mixin.py:149} INFO - +---------+------------------+
|sensor_id|         avg_value|
+---------+------------------+
| sensor_0| 25.04885340314137|
| sensor_1|24.914106776180706|
| sensor_4| 25.02256948085999|
| sensor_2| 25.06287076271186|
| sensor_3|25.125433186490454|
+---------+------------------+
[2025-08-18T13:23:20.579+0000] {logging_mixin.py:149} INFO - ===== GUARDANDO RESULTADOS EN POSTGRES =====
[2025-08-18T13:25:19.622+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2025-08-18T13:26:52.017+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 38066. PIDs of all processes in the group: [38073, 38081, 38066]
[2025-08-18T13:26:52.226+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 38066
[2025-08-18T13:26:53.149+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-08-18T13:26:53.417+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-08-18T13:26:57.447+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-08-18T13:26:57.469+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1519, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2025-08-18T13:26:57.502+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-08-18T13:26:57.909+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_pipeline.py", line 47, in process_with_spark
    .mode("overwrite") \
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 966, in save
    self._jwrite.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o44.save
[2025-08-18T13:27:03.344+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=nitro_data_pipeline, task_id=process_with_spark, execution_date=20250818T131202, start_date=20250818T131208, end_date=20250818T132703
[2025-08-18T13:27:03.716+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 385 for task process_with_spark (An error occurred while calling o44.save; 38066)
[2025-08-18T13:27:03.784+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=38066, status='terminated', exitcode=1, started='13:12:08') (38066) terminated with exit code 1
[2025-08-18T13:27:03.794+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=38081, status='terminated', started='13:12:09') (38081) terminated with exit code None
[2025-08-18T13:27:03.794+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=38073, status='terminated', started='13:12:09') (38073) terminated with exit code None
